name: Build better-sqlite3.node (Win32, Node14)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022 # Using windows-2022 due to windows-2019 deprecation

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 14 x86
        uses: actions/setup-node@v4
        with:
          node-version: 14.15.3 # Updated to specific Node.js version as requested
          architecture: x86

      - name: Install Python (for node-gyp)
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' # Node 14 is more compatible with Python 3.8

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --version=16.11.23.0
          choco install visualstudio2019-workload-vctools --version=1.0.1
        env:
          ChocolateyUseWindowsCompression: 'true'

      - name: Install node-gyp and dependencies
        run: |
          npm install -g node-gyp@8.4.1 # Specific version for Node 14 compatibility
          npm config set msvs_version 2019 # Set VS 2019 explicitly for Windows 7 compatibility

      - name: Install better-sqlite3@7.6.2
        run: npm install better-sqlite3@7.6.2 --build-from-source --electron-version=11.5.0
        env:
          npm_config_arch: ia32 # Explicitly set 32-bit architecture

      - name: Package .node
        run: |
          mkdir output
          copy node_modules\better-sqlite3\build\Release\better_sqlite3.node output\
          powershell -Command "Compress-Archive -Path output\* -DestinationPath better_sqlite3_win32_node14.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: better_sqlite3_win32_node14
          path: better_sqlite3_win32_node14.zip
